### ISSUE TITLE
石操作をする関数

### ISSUE THREAD

**Issue by wata21905** [hhyuga201515/StonePavCrafter#10]
## 概要
これはstone_rotate関数Issueです。
回転: 0度, 90度, 180度, 270度
引数として、石番号、表裏操作('H', 'T')、回転操作(0, 90, 180, 270)
戻り値は、なし

## 変更点
- [ ] 石番号を引数として、どの石を操作するか決める
- [ ] 操作後の石を現在の石と置き換える

## 追加タスク
- [x] 操作情報をもとに、石を操作して操作後の石を返す関数の作成

### 親Issue
---
#7 
 
#### 備考
---
継承 #21 #22

**Comment by hhyuga201515** [comment]
仕様変更したので確認よろ

**Comment by wata21905** [comment]
回転の関数と表裏の関数とわけてもいいっすか??

**Comment by hhyuga201515** [comment]
分けるのでClose

**Comment by hhyuga201515** [comment]
結局1つにしたほうが、self.origin_stonesからの兼ね合いに都合がよかった。
