### ISSUE TITLE
問題ファイルを読み込む関数

### ISSUE THREAD

**Issue by wata21905** [hhyuga201515/StonePavCrafter#8]
## 概要
これはload関数Issueです。  
引数に指定されたファイル名のファイルを読み込んで、敷地、石を、
self.site, self.stone_num, self.stones, self.origin_stonesに保存する。

敷地: 32x32の2次元リストで返す。
石情報(a): 石の個数を返す。
石情報(b): 8x8の石の形状を3次元リストで返す。

## 変更点
- [x] 各情報を、メンバ変数に保存するようにする
- [x] 初期状態を記憶しておくため、deepcopyで初期状態を保存しておく
## 追加タスク
- [x] 敷地情報、石情報を返す関数を作る

### 親Issue
---
#7 
 
#### 備考
---

**Comment by hhyuga201515** [comment]
石の状態は、
0: 何もなし
1: ブロック
2: 障害物
ってことにしてほしい

**Comment by wata21905** [comment]
それは石状態(b)のことを言ってる??

**Comment by hhyuga201515** [comment]
ごめん、敷地情報の話。
石情報(b)には、障害物はないはず。

**Comment by wata21905** [comment]
それもそーやな笑
がんばってみる!!!

**Comment by wata21905** [comment]
え、でも0と2はどーやって判別したらいいんや??
ファイルには障害物のことも1と表してあると思うし…

**Comment by hhyuga201515** [comment]
ファイルには、空のマスと、障害物があるマスの２つしかないから、0と1で書かれてるだけで、
敷地情報として配列に代入するときに、0のところは0、1のところは2に変換してやればいいだけ

**Comment by wata21905** [comment]
そしたら1はできんくないか??

**Comment by hhyuga201515** [comment]
1は石を敷いたときに使われる

**Comment by wata21905** [comment]
いや、まじでよーわからん…

**Comment by hhyuga201515** [comment]
敷地情報、石情報等などに関しては、各座標の状態を表すときに、
0: 空
1: ブロック
2: 障害物
で表現するってこと

**Comment by wata21905** [comment]
たぶんわかったんやけど、コードが全然かけませぬ
書きたいように書いてもエラーばっかや

**Comment by hhyuga201515** [comment]
今学校？

**Comment by wata21905** [comment]
教室なうやでい

**Comment by hhyuga201515** [comment]
仕様変更したから確認よろ

**Comment by hhyuga201515** [comment]
動作確認済み
