### ISSUE TITLE
石を敷くことができるか判定する関数

### ISSUE THREAD

**Issue by wata21905** [hhyuga201515/StonePavCrafter#9]
## 概要
これはjudge_pave関数Issueです。  
石を敷くことができる場合はTrue。それ以外はFalseを返す。
引数として、石番号、どこに石を置くか(x, y座標)。

## 追加タスク
- [ ] 敷地情報、石、座標情報をもとに、石が置けるかどうか判定する関数を作る

### 親Issue
---
#7 
 
#### 備考
---

**Comment by hhyuga201515** [comment]
functionラベル削除のためclose
